language: php

php:
    - 7.2
    - 7.3

notifications:
    email: false

matrix:
    fast_finish: true

before_install:
    - echo 'Europe/Berlin' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - sudo apt-get update

before_script:
    - php composer.phar install

script:
    - php composer.phar phpunit
