language: php
addons:
    sonarcloud:
        organization: "sundayhaxors"
        branches:
            - master
php:
    - 7.2
    - 7.3

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.sonar/cache

matrix:
    fast_finish: true

before_install:
    - echo 'Europe/Berlin' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata

before_script:
    - composer install

script:
    - composer phpcs
    - composer phpstan
    - composer phpunit
    - sonar-scanner
