name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-binary:
          - php7.1
          - php7.2

    steps:
    - uses: actions/checkout@v1
    - name: Check PHP Version 
      run: ${{ matrix.php-binary }} -v
    - name: Check Composer
      run: ${{ matrix.php-binary }} $(which composer) -V
    - name: PHPUnit
      run: ${{ matrix.php-binary }} $(which composer) phpunit
