name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.php_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.1, 7.2]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use PHP ${{ matrix.php_version }}
      uses: actions/setup-php@master
      with:
        version: ${{ matrix.php_version }}
        
    - name: Check PHP Version 
      run: php -v
    - name: Check Composer
      run: composer -V
