name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check PHP
      run: php -v
    - name: Check PHP 5.6
      run: php5.6 -v
    - name: Check PHP 7.0
      run: php7.0 -v
    - name: Check PHP 7.1
      run: php7.1 -v
    - name: Check PHP 7.2
      run: php7.2 -v
    - name: Check PHP 7.3
      run: php7.3 -v
    - name: Check PHP 7.4
      run: php7.4 -v
    - name: Check Composer
      run: composer -V
